language: python

# Specify the Python version you want to use
python:
  - 3.9
install:
  - pip install -r requirements.txt

before_script:
  -cd mysite
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
