language: python

# Specify the Python version you want to use
python:
  - 3.8
install:
  - pip install -r requirements.txt
  - mkdir ./coveragePackage
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./coveragePackage

before_script:
  - python manage.py migrate


script:
  - black --check .
  - flake8 . --max-line-length=100
  - coverage run manage.py test
  - coverage xml
  - ./coveragePackage/coveralls report --repo-token=$COVERALLTOKEN ./coverage.xml

  deploy:
    provider: elasticbeanstalk
    access_key_id:
    secure: "Encrypted <access-key-id>="
    secret_access_key:
    secure: "Encypted <secret-access-key>="
    region: "us-east-1"
    app: "example-app-name"
    env: "example-app-environment"
    bucket_name: "the-target-S3-bucket"
