language: python

# Specify the Python version you want to use
python:
  - 3.8
install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 . --max-line-length=99
